### ISSUE TITLE
Checkboxes and radio buttons appear clipped in Firefox

### ISSUE THREAD

**Issue by astrotim** [WestpacCXTeam/GUI-source#128]
Firefox 40.0.2 on OSX Yosemite 10.10.4

<img width="657" alt="radios" src="https://cloud.githubusercontent.com/assets/2671362/9456680/12cb50cc-4b1e-11e5-8092-9bcc324fb773.png">

<img width="356" alt="checkbox" src="https://cloud.githubusercontent.com/assets/2671362/9456681/14d5feda-4b1e-11e5-8895-fafd469aec42.png">

**Comment by dominikwilkowski** [comment]
To be fixed in v1.0.1 with:

```css
.checkbox {
    height: 32px;
}
```

and

```css
.radio {
    height: 32px;
}
```
