### ISSUE TITLE
Input placeholder color in IE

### ISSUE THREAD

**Issue by BastienZag** [WestpacCXTeam/GUI-source#152]
In IE, placeholders for input fields are black.
That will be good to have the same color as chrome (grey).

```CSS
&:-ms-input-placeholder {
    color: @
}
```
