### ISSUE TITLE
buttons group with icons don't change fill when selected

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#185]
Needs fix:

```css
.btn-group-input:checked+.btn .icons-background {
	fill: #fff;
}
```
