### ISSUE TITLE
select need block class

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#186]
There is no block class for the select element.

```css
.input-field-select-wrapper.input-field-select-block {
	display: block;

	.input-field-select {
		width: 100%;
	}
}
```
