### ISSUE TITLE
Icons in text classes should automatically tint

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#190]
e.g.
```css
.text-info {
	.icons-background {
		fill: @color-Info;
	}
}
```
