### ISSUE TITLE
Button groups broken in Safari

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#191]
![screen shot 2016-01-29 at 10 33 59 am](https://cloud.githubusercontent.com/assets/1266923/12662332/d7cbae50-c673-11e5-88a1-1ae1343f118c.png)

Only fix I found so far:

```css
.btn-group {
	overflow: hidden;

	.btn-group-item {
		float: left;
	}
}
```

But `btn-block` needs fixing then

**Comment by dominikwilkowski** [comment]
The issue is San Fransisco...

```css
.btn-group {
	font-family: sans-serif;

	.btn-group-item {
		font-family: @fontfamily;
	}
}
```
