### ISSUE TITLE
create a nicer fallback for icons in IE8

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#192]
So it turns out you can use `zoom: 0.5;` in IE8 to our advantage.

```css
.icon {
	&.icon-size-sm {
		.ie8 & {
			zoom: 0.5;
			width: 32px;
			height: 32px;
		}
	}

	&.icon-size-lg {
		.ie8 & {
			zoom: 2;
			width: 32px;
			height: 32px;
		}
	}
}
```

This would resize the pngs in each sizes... Easy enough
