### ISSUE TITLE
select in IE8/IE9 could look better

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#193]
By resetting the padding for IE8 and IE9 only we get a better look:

for large
```css
.ie8 & {
	padding: 7px;
}
```
