### ISSUE TITLE
Alert icons broken in Safari in xs

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#194]
The icons need a min-width to prevent breaking:

```css
.alert-icon.icon-size-sm {
	min-width: 16px;
}

.alert-icon.icon-size-md {
	min-width: 32px;
}

.alert-icon.icon-size-lg {
	min-width: 64px;
}
```
