### ISSUE TITLE
Make less brand variable a default

### ISSUE THREAD

**Issue by dominikwilkowski** [WestpacCXTeam/GUI-source#203]
Prerequisites
-------------

* [ YES ] Can you reproduce the problem in the [testing area of the GUI](http://westpaccxteam.github.io/GUI-source/)?
* [ YES ] Are you running the latest version of the affected module?
* [ YES ] Did you check if the issue already exists ([open](https://github.com/WestpacCXTeam/GUI-source/issues) or
	[closed](https://github.com/WestpacCXTeam/GUI-source/issues?q=is%3Aissue+is%3Aclosed))?

Description
-----------

Currently we brand each less file in the bottom with e.g.: `._input-fields( BOM );`. This prevents us to use the same file in another brand.
It would be better to go with a default value so it can be overwritten if it is declared.
I made a test case and think this is how it should work:

In the module less file
```less
//////////////////////////////////////| input-fields mixin
._input-fields( @brand: [Brand] ) {
	some: code;
}
// and remove the mixin call in the bottom
```

In the `gui.less` file
```less
@brand: BOM;

/* ---------------------------------------| MODULES |--------------------------------------- */
@import [core files];
@import 'input-fields.less';
._input-fields( @brand );
```

This way a change in brand would be as much work as changing that one variable. We also provide a fallback if someone forgets the brand. `._input-fields();` will fallback to it's default variable which can be hardcoded into the module less file.
@BastienZag was asking for this feature as well for `YoDa`. What'd you think buddy?

Steps to Reproduce
------------------

1. You download the blender zip
2. Your module file is branded and that brand is hardcoded

**Expected behavior:**
I can use the very same less file in another brand

**Actual behavior:**
I have to download each brand less to get the hardcoded variable

Versions
--------

ALL

Examples
-----------

[small CodePen test](http://codepen.io/dominikwilkowski/pen/yemByg)

**Comment by BastienZag** [comment]
Looks good.

This is a really good idea. Keeping the brand in one file will facilitate the brand switching during a grunt task.

Thanks

**Comment by dominikwilkowski** [comment]
I have investigated further and I think this is even better:

In the module less file
```less
@brand: BOM; //hardcoded brand value

//////////////////////////////////////| input-fields mixin
._input-fields( @brand: [Brand] ) {
	some: code;
}

._input-fields( @brand ); //calling the variable
```

In the `gui.less` file
```less
@brand: BOM;

/* ---------------------------------------| MODULES |--------------------------------------- */
@import [core files];
@import 'input-fields.less';
```

This will enable us to have each module less file autonomous as it will run by itself without the need to call the mixin plus you can always overwrite the `@brand` variable by including it inside the `gui.less` file thanks to [lazy loading](http://lesscss.org/features/#variables-feature-lazy-loading) in less.
The outcome for you @BastienZag is still the same. You can change the brand by changing just one variable.

Thoughts?
